# Generated by Django 2.2.2 on 2020-08-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
