# Generated by Django 2.2.2 on 2020-09-26 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamount',
            name='user',
            field=models.ForeignKey(default='3085413d-109c-45d7-9f93-ced14e5f8925', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
