# Generated by Django 2.2.2 on 2020-09-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_delete_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
