# Generated by Django 2.2.2 on 2020-07-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_bookmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='user_rates',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_on', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='books.BookModel')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
