# Generated by Django 2.2.2 on 2020-07-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200716_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='price',
        ),
    ]
