# Generated by Django 2.2.2 on 2020-07-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='price',
        ),
    ]
