# Generated by Django 2.2.2 on 2020-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
