# Generated by Django 2.2.2 on 2020-07-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200724_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
