# Generated by Django 2.2.2 on 2020-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_bookmodel_is_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategorymodel',
            name='cover_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
