# Generated by Django 2.2.2 on 2020-08-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200803_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_category',
        ),
    ]
