# Generated by Django 2.2.2 on 2020-08-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200804_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_category',
        ),
    ]
