# Generated by Django 2.2.2 on 2020-08-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200804_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
