# Generated by Django 2.2.2 on 2020-08-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20200816_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='body',
        ),
    ]
