# Generated by Django 2.2.2 on 2020-08-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_auto_20200816_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='body',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
