# Generated by Django 2.2.2 on 2020-08-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20200816_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
