# Generated by Django 2.2.2 on 2020-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
