# Generated by Django 2.2.2 on 2020-08-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20200824_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
