# Generated by Django 2.2.2 on 2020-07-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200703_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_access',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'SCHOOL'), ('READER', 'READER')], max_length=255, null=True),
        ),
    ]
