# Generated by Django 2.2.2 on 2020-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200703_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_access',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'SCHOOL'), ('USER', 'USER')], max_length=255, null=True),
        ),
    ]
