# Generated by Django 2.2.2 on 2020-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_category',
            name='pic',
            field=models.ImageField(null=True, upload_to='age/'),
        ),
    ]
