# Generated by Django 2.2.2 on 2020-07-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
