# Generated by Django 2.2.2 on 2020-09-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_user_is_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'SCHOOL'), ('READER', 'READER')], max_length=255, null=True),
        ),
    ]
